"""Generate an auditor-ready PDF compliance evidence report using fpdf2."""
from __future__ import annotations

from datetime import datetime
from typing import Any

from fpdf import FPDF

from app.models.aws_account import AwsAccount

_REPLACEMENTS = {
    "—": "-",
    "–": "-",
    "…": "...",
    "·": ".",
    "\u2019": "'",
    "\u2018": "'",
    "\u201c": '"',
    "\u201d": '"',
}

_FRAMEWORK_LABELS = {
    "soc2": "SOC 2 Trust Services Criteria",
    "cis_aws_l1": "CIS Amazon Web Services Foundations Benchmark - Level 1",
    "iso27001": "ISO 27001:2022 Annex A",
}

_FRAMEWORK_BADGE = {
    "soc2": "SOC 2 Evidence Report",
    "cis_aws_l1": "CIS AWS Evidence Report",
    "iso27001": "ISO 27001 Evidence Report",
}

_CONTROL_STATUS = {
    "pass": {"label": "PASS", "fill": (220, 252, 231), "text": (21, 128, 61)},
    "fail": {"label": "NEEDS REVIEW", "fill": (254, 243, 199), "text": (180, 83, 9)},
    "no_data": {"label": "NO DATA", "fill": (244, 244, 245), "text": (113, 113, 122)},
}

_EVIDENCE_STATUS = {
    "complete": {"label": "COMPLETE", "fill": (219, 234, 254), "text": (29, 78, 216)},
    "partial": {"label": "PARTIAL", "fill": (254, 243, 199), "text": (180, 83, 9)},
    "missing": {"label": "MISSING", "fill": (244, 244, 245), "text": (113, 113, 122)},
}

_SEVERITY_COLOR = {
    "critical": (185, 28, 28),
    "high": (220, 38, 38),
    "medium": (217, 119, 6),
    "low": (113, 113, 122),
}


def _s(text: str) -> str:
    for ch, rep in _REPLACEMENTS.items():
        text = text.replace(ch, rep)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class VigilReportPDF(FPDF):
    def __init__(self, report_id: str, generated_at: datetime):
        super().__init__()
        self.report_id = report_id
        self.generated_at = generated_at

    def footer(self) -> None:
        self.set_y(-16)
        self.set_draw_color(228, 228, 231)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(2)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(82, 82, 91)
        self.cell(
            0,
            4,
            _s(
                f"Generated by Vigil  |  Read-only evidence collection  |  "
                f"Not a compliance attestation  |  Report ID: {self.report_id}"
            ),
            align="C",
        )
        self.ln(3)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(113, 113, 122)
        self.cell(
            0,
            3,
            _s(
                "This report is evidence generated from read-only source-system APIs. "
                "It supports audit review but is not a guarantee of compliance or certification."
            ),
            align="C",
        )


def _draw_pill(pdf: FPDF, label: str, style: dict[str, tuple[int, int, int]], w: float = 0, h: float = 5.5) -> None:
    fill = style["fill"]
    text = style["text"]
    pdf.set_fill_color(*fill)
    pdf.set_text_color(*text)
    pdf.set_font("Helvetica", "B", 7)
    if w <= 0:
        w = pdf.get_string_width(label) + 6
    x = pdf.get_x()
    y = pdf.get_y()
    pdf.rect(x, y + 0.3, w, h, style="F")
    pdf.set_xy(x, y + 1.0)
    pdf.cell(w, 4, label, align="C")
    pdf.set_xy(x + w, y)


def _draw_summary_card(
    pdf: FPDF,
    x: float,
    y: float,
    w: float,
    h: float,
    value: str,
    label: str,
    accent: tuple[int, int, int],
) -> None:
    pdf.set_xy(x, y)
    pdf.set_fill_color(255, 255, 255)
    pdf.set_draw_color(228, 228, 231)
    pdf.rect(x, y, w, h, style="FD")
    pdf.set_fill_color(*accent)
    pdf.rect(x, y, 2.5, h, style="F")
    pdf.set_xy(x + 5, y + 4)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(24, 24, 27)
    pdf.cell(w - 7, 8, value, new_x="LMARGIN", new_y="NEXT")
    pdf.set_x(x + 5)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(82, 82, 91)
    pdf.cell(w - 7, 4, _s(label))


def _resource_label(arn: str) -> str:
    if arn.startswith("github://"):
        return arn.replace("github://repo/", "")
    if arn.startswith("gitlab://"):
        return arn.replace("gitlab://repo/", "")
    if "/" in arn:
        return arn.rsplit("/", 1)[-1]
    return arn[:48]


def _severity_counts(findings: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for f in findings:
        sev = (f.get("severity") or "medium").lower()
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def _fmt_date(iso: str | None) -> str:
    if not iso:
        return "-"
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%Y-%m-%d")
    except ValueError:
        return iso[:10]


def build_pdf(
    acc: AwsAccount,
    framework: str,
    period_days: int,
    generated_at: datetime,
    control_results: list[dict[str, Any]],
    *,
    since: datetime | None = None,
    evidence_sources: list[str] | None = None,
    report_id: str | None = None,
) -> bytes:
    rid = report_id or "SAMPLE"
    pdf = VigilReportPDF(rid, generated_at)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(16, 16, 16)
    pdf.add_page()

    # Header wordmark + badge
    pdf.set_fill_color(24, 24, 27)
    pdf.rect(pdf.l_margin, pdf.get_y(), 28, 10, style="F")
    pdf.set_xy(pdf.l_margin + 4, pdf.get_y() + 2.5)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(20, 5, "Vigil")

    badge = _FRAMEWORK_BADGE.get(framework, "Compliance Evidence Report")
    pdf.set_xy(pdf.l_margin + 34, pdf.get_y() - 2.5)
    pdf.set_fill_color(238, 242, 255)
    pdf.set_text_color(67, 56, 202)
    pdf.set_font("Helvetica", "B", 9)
    badge_w = pdf.get_string_width(badge) + 8
    pdf.rect(pdf.l_margin + 34, pdf.get_y(), badge_w, 7, style="F")
    pdf.set_xy(pdf.l_margin + 38, pdf.get_y() + 1.5)
    pdf.cell(badge_w - 8, 4, _s(badge))

    pdf.ln(12)
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(24, 24, 27)
    pdf.cell(0, 10, "Compliance Evidence Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(82, 82, 91)
    pdf.cell(0, 5, _s(_FRAMEWORK_LABELS.get(framework, framework.upper())), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Metadata card
    card_y = pdf.get_y()
    card_h = 28
    pdf.set_fill_color(249, 250, 251)
    pdf.set_draw_color(228, 228, 231)
    pdf.rect(pdf.l_margin, card_y, pdf.epw, card_h, style="FD")
    period_end = generated_at.date()
    period_start = since.date() if since else period_end
    sources = evidence_sources or ["AWS IAM", "AWS CloudTrail", "AWS Config"]
    meta_rows = [
        ("Account", f"{_s(acc.label)} ({acc.account_id or 'unknown'})"),
        ("Audit period", f"{period_start} to {period_end} ({period_days} days)"),
        ("Generated", generated_at.strftime("%Y-%m-%d %H:%M UTC")),
        ("Evidence sources", ", ".join(sources)),
        ("Report ID", rid),
    ]
    col_w = pdf.epw / 2
    for i, (label, value) in enumerate(meta_rows):
        col = i % 2
        row = i // 2
        x = pdf.l_margin + 4 + col * col_w
        y = card_y + 4 + row * 8
        pdf.set_xy(x, y)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(113, 113, 122)
        pdf.cell(26, 4, _s(label.upper()))
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(39, 39, 42)
        pdf.cell(col_w - 30, 4, _s(value))
    pdf.set_y(card_y + card_h + 4)

    pdf.set_draw_color(212, 212, 216)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # Executive summary
    passed = sum(1 for r in control_results if r["status"] == "pass")
    failed = sum(1 for r in control_results if r["status"] == "fail")
    no_data = sum(1 for r in control_results if r["status"] == "no_data")
    total = len(control_results)
    score_pct = round((passed / total) * 100) if total else 0

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(24, 24, 27)
    pdf.cell(0, 7, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    card_w = (pdf.epw - 9) / 4
    card_h = 22
    y0 = pdf.get_y()
    _draw_summary_card(pdf, pdf.l_margin, y0, card_w, card_h, f"{score_pct}%", "Pass rate", (34, 197, 94))
    _draw_summary_card(pdf, pdf.l_margin + card_w + 3, y0, card_w, card_h, str(passed), "Passed controls", (34, 197, 94))
    _draw_summary_card(pdf, pdf.l_margin + 2 * (card_w + 3), y0, card_w, card_h, str(failed), "Needs review", (239, 68, 68))
    _draw_summary_card(pdf, pdf.l_margin + 3 * (card_w + 3), y0, card_w, card_h, str(no_data), "No data", (161, 161, 170))
    pdf.set_y(y0 + card_h + 8)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(82, 82, 91)
    pdf.multi_cell(
        pdf.epw,
        4.5,
        _s(
            "Control status reflects open findings mapped to each control. "
            "Evidence status reflects whether source-system snapshots were collected for that control, "
            "independent of pass/fail."
        ),
    )
    pdf.ln(4)

    # Control table
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(24, 24, 27)
    pdf.cell(0, 7, "Control Overview", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    col_w = [20, 68, 28, 28, 18]
    pdf.set_fill_color(39, 39, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 8)
    for i, h in enumerate(["Control", "Title", "Status", "Evidence", "Open"]):
        pdf.cell(col_w[i], 8, h, border=0, fill=True, align="C" if i >= 2 else "L")
    pdf.ln()

    for idx, r in enumerate(control_results):
        if pdf.get_y() > 255:
            pdf.add_page()
        row_h = 8
        fill = idx % 2 == 0
        bg = (249, 250, 251) if fill else (255, 255, 255)
        pdf.set_fill_color(*bg)
        y_row = pdf.get_y()

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(39, 39, 42)
        pdf.cell(col_w[0], row_h, _s(r["control_id"]), border=0, fill=fill)

        title = _s(r["title"])
        if len(title) > 52:
            title = title[:49] + "..."
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(col_w[1], row_h, title, border=0, fill=fill)

        ctrl_style = _CONTROL_STATUS.get(r["status"], _CONTROL_STATUS["no_data"])
        pdf.set_xy(pdf.l_margin + col_w[0] + col_w[1] + 2, y_row + 1.2)
        _draw_pill(pdf, ctrl_style["label"], ctrl_style, w=col_w[2] - 4)

        ev_style = _EVIDENCE_STATUS.get(r.get("evidence_status", "missing"), _EVIDENCE_STATUS["missing"])
        pdf.set_xy(pdf.l_margin + col_w[0] + col_w[1] + col_w[2] + 2, y_row + 1.2)
        _draw_pill(pdf, ev_style["label"], ev_style, w=col_w[3] - 4)

        pdf.set_xy(pdf.l_margin + sum(col_w[:4]), y_row)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(39, 39, 42)
        pdf.cell(col_w[4], row_h, str(r["finding_count"]), border=0, fill=fill, align="C")
        pdf.ln(row_h)

    pdf.ln(6)

    # Controls requiring review
    review_controls = [r for r in control_results if r["status"] == "fail"]
    if review_controls:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(24, 24, 27)
        pdf.cell(0, 8, "Controls Requiring Review", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for r in review_controls:
            if pdf.get_y() > 230:
                pdf.add_page()

            card_y = pdf.get_y()
            pdf.set_draw_color(228, 228, 231)
            pdf.line(pdf.l_margin, card_y, pdf.w - pdf.r_margin, card_y)
            pdf.ln(3)

            pdf.set_x(pdf.l_margin + 2)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(24, 24, 27)
            pdf.cell(0, 6, _s(f"{r['control_id']}  {r['title']}"), new_x="LMARGIN", new_y="NEXT")

            pdf.set_x(pdf.l_margin + 4)
            _draw_pill(pdf, "NEEDS REVIEW", _CONTROL_STATUS["fail"], w=28)
            pdf.ln(6)

            pdf.set_x(pdf.l_margin + 4)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(113, 113, 122)
            pdf.cell(18, 4, "OBJECTIVE")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(63, 63, 70)
            pdf.multi_cell(pdf.epw - 8, 4.5, _s(r["description"][:280]))

            pdf.set_x(pdf.l_margin + 4)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(113, 113, 122)
            pdf.cell(18, 4, "REASON")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(180, 83, 9)
            pdf.multi_cell(pdf.epw - 8, 4.5, _s(r.get("review_reason") or r.get("status_note", "")))

            counts = _severity_counts(r.get("findings") or [])
            if counts:
                pdf.set_x(pdf.l_margin + 4)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(113, 113, 122)
                pdf.cell(0, 4, "FINDINGS BY SEVERITY", new_x="LMARGIN", new_y="NEXT")
                pdf.set_x(pdf.l_margin + 4)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(63, 63, 70)
                parts = [f"{k.upper()}: {v}" for k, v in sorted(counts.items())]
                pdf.cell(0, 4, "  |  ".join(parts), new_x="LMARGIN", new_y="NEXT")

            findings = r.get("findings") or []
            if findings:
                pdf.ln(2)
                pdf.set_x(pdf.l_margin + 4)
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(113, 113, 122)
                pdf.cell(0, 4, "TOP FINDINGS", new_x="LMARGIN", new_y="NEXT")
                for f in findings[:5]:
                    pdf.ln(1)
                    pdf.set_x(pdf.l_margin + 6)
                    sev = (f.get("severity") or "medium").lower()
                    pdf.set_font("Helvetica", "B", 8)
                    pdf.set_text_color(*_SEVERITY_COLOR.get(sev, (113, 113, 122)))
                    pdf.cell(14, 4, f"[{sev.upper()}]")
                    pdf.set_font("Helvetica", "B", 8)
                    pdf.set_text_color(39, 39, 42)
                    pdf.cell(0, 4, _resource_label(f.get("resource_arn", "")), new_x="LMARGIN", new_y="NEXT")
                    pdf.set_x(pdf.l_margin + 20)
                    pdf.set_font("Helvetica", "", 8)
                    pdf.set_text_color(63, 63, 70)
                    pdf.multi_cell(pdf.epw - 24, 4, _s(f"Issue: {f.get('title', '')}"))
                    pdf.set_x(pdf.l_margin + 20)
                    pdf.set_font("Helvetica", "", 7)
                    pdf.set_text_color(113, 113, 122)
                    pdf.cell(
                        0,
                        3.5,
                        _s(
                            f"Resource: {f.get('resource_arn', '')}  |  "
                            f"First seen: {_fmt_date(f.get('first_seen'))}  |  "
                            f"Last seen: {_fmt_date(f.get('last_seen'))}"
                        ),
                        new_x="LMARGIN",
                        new_y="NEXT",
                    )
                if len(findings) > 5:
                    pdf.set_x(pdf.l_margin + 20)
                    pdf.set_font("Helvetica", "I", 8)
                    pdf.set_text_color(113, 113, 122)
                    pdf.cell(
                        0,
                        4,
                        _s(f"+ {len(findings) - 5} more findings in controls/{r['control_id']}/findings.json"),
                        new_x="LMARGIN",
                        new_y="NEXT",
                    )

            pdf.ln(2)
            pdf.set_x(pdf.l_margin + 4)
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(113, 113, 122)
            pdf.cell(0, 4, "EVIDENCE ARTIFACTS", new_x="LMARGIN", new_y="NEXT")
            pdf.set_x(pdf.l_margin + 6)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(29, 78, 216)
            for artifact in (
                f"controls/{r['control_id']}/findings.json",
                f"controls/{r['control_id']}/snapshots.json",
                f"controls/{r['control_id']}/exceptions.json",
                f"controls/{r['control_id']}/summary.json",
            ):
                pdf.cell(0, 4, artifact, new_x="LMARGIN", new_y="NEXT")
                pdf.set_x(pdf.l_margin + 6)

            pdf.ln(4)
            pdf.set_draw_color(228, 228, 231)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(4)

    # Evidence sources section
    if pdf.get_y() > 240:
        pdf.add_page()
    pdf.ln(4)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(24, 24, 27)
    pdf.cell(0, 7, "Evidence Sources", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(63, 63, 70)
    for line in [
        *sources,
        "Generated from read-only API access (no write permissions)",
        "Raw JSON evidence included in ZIP under controls/<control_id>/",
        "Timeline and source manifest included as timeline.csv and source_manifest.json",
    ]:
        pdf.set_x(pdf.l_margin + 2)
        pdf.cell(4, 5, "-")
        pdf.multi_cell(pdf.epw - 6, 5, _s(line))

    return bytes(pdf.output())
