from app.checks import (
    github_org_mfa,
    github_org_dormant,
    github_org_outside_collaborators,
    github_repo_no_protection,
    github_repo_no_env_protection,
    github_repo_no_codeowners,
    github_repo_self_merge,
    github_repo_insufficient_reviews,
    gitlab_org_mfa,
    gitlab_org_dormant,
    gitlab_repo_no_protection,
    gitlab_repo_self_merge,
    gitlab_repo_insufficient_reviews,
    gitlab_repo_no_codeowners,
    access_analyzer_not_enabled,
    aws_account_contact_incomplete,
    aws_account_security_contact_missing,
    iam_server_certificate_expired,
    iam_cloudshell_access,
    access_key_multiple_active,
    access_key_no_rotation,
    cloudtrail_no_kms,
    cloudtrail_not_enabled,
    cloudtrail_no_log_validation,
    config_not_enabled,
    aws_config_rules_non_compliant,
    ec2_ebs_encryption_default,
    ec2_ebs_volume_unencrypted,
    ec2_imdsv2_not_required,
    guardduty_not_enabled,
    guardduty_open_findings,
    iam_access_inventory_gap,
    iam_role_external_trust,
    iam_access_key_unused_45d,
    iam_password_policy_weak,
    iam_support_role,
    iam_perm_granted_vs_used,
    iam_root_access_keys,
    iam_root_no_mfa,
    iam_root_usage,
    iam_user_credentials_unused_45d,
    iam_user_no_mfa,
    iam_user_direct_policy,
    kms_no_rotation,
    kms_key_policy_wildcard,
    rds_no_encryption,
    rds_no_automated_backup,
    rds_publicly_accessible,
    role_trust_wildcard,
    role_unassumed_90d,
    role_unused_services,
    role_wildcard_action,
    iam_role_full_admin,
    iam_policy_wildcard_resource,
    iam_policy_unattached,
    s3_account_public_access,
    s3_no_https_policy,
    s3_no_kms,
    s3_no_logging,
    s3_public_access,
    sg_default_allows_traffic,
    sg_unrestricted_rdp,
    sg_unrestricted_ssh,
    securityhub_not_enabled,
    vpc_no_flow_logs,
    s3_no_default_encryption,
    s3_no_mfa_delete,
    ebs_snapshot_public,
    ebs_snapshot_unencrypted,
    ec2_ami_public,
    ec2_ami_aged,
    cloudtrail_s3_bucket_public,
    cloudtrail_no_cloudwatch,
    cloudtrail_s3_no_logging,
    acm_cert_expiring,
    lambda_deprecated_runtime,
    lambda_no_dlq,
    rds_no_deletion_protection,
    rds_no_multi_az,
    secrets_no_rotation,
    ssm_plaintext_secret,
    elb_no_access_logs,
    elb_weak_tls,
    dynamodb_no_pitr,
    dynamodb_no_encryption,
    sns_no_encryption,
    sqs_no_encryption,
)

ALL_CHECKS = [
    # root (critical — run first)
    iam_root_access_keys,
    iam_root_no_mfa,
    iam_root_usage,
    # IAM account
    iam_password_policy_weak,
    iam_support_role,
    # IAM users
    iam_user_credentials_unused_45d,
    iam_access_key_unused_45d,
    access_key_no_rotation,
    access_key_multiple_active,
    iam_user_no_mfa,
    iam_user_direct_policy,
    # IAM roles / policies
    role_unassumed_90d,
    role_wildcard_action,
    iam_role_full_admin,
    iam_perm_granted_vs_used,
    iam_policy_wildcard_resource,
    iam_policy_unattached,
    iam_role_external_trust,
    iam_access_inventory_gap,
    role_unused_services,
    role_trust_wildcard,
    # S3
    s3_account_public_access,
    s3_public_access,
    s3_no_https_policy,
    s3_no_kms,
    s3_no_logging,
    # KMS
    kms_no_rotation,
    kms_key_policy_wildcard,
    # CloudTrail
    cloudtrail_not_enabled,
    cloudtrail_no_log_validation,
    cloudtrail_no_kms,
    # GuardDuty
    guardduty_not_enabled,
    guardduty_open_findings,
    # Access Analyzer
    access_analyzer_not_enabled,
    aws_account_contact_incomplete,
    aws_account_security_contact_missing,
    iam_server_certificate_expired,
    iam_cloudshell_access,
    # AWS Config
    config_not_enabled,
    aws_config_rules_non_compliant,
    # Security Hub
    securityhub_not_enabled,
    # VPC
    vpc_no_flow_logs,
    # EC2 Security Groups
    sg_unrestricted_ssh,
    sg_unrestricted_rdp,
    sg_default_allows_traffic,
    # EC2 Instances
    ec2_imdsv2_not_required,
    ec2_ebs_encryption_default,
    ec2_ebs_volume_unencrypted,
    # RDS
    rds_publicly_accessible,
    rds_no_encryption,
    rds_no_automated_backup,
    # GitHub identity
    github_org_mfa,
    github_org_dormant,
    github_org_outside_collaborators,
    github_repo_no_protection,
    github_repo_no_env_protection,
    github_repo_no_codeowners,
    github_repo_self_merge,
    github_repo_insufficient_reviews,
    # GitLab identity
    gitlab_org_mfa,
    gitlab_org_dormant,
    gitlab_repo_no_protection,
    gitlab_repo_self_merge,
    gitlab_repo_insufficient_reviews,
    gitlab_repo_no_codeowners,
    # AWS gap checks (session 18)
    s3_no_default_encryption,
    s3_no_mfa_delete,
    ebs_snapshot_public,
    ebs_snapshot_unencrypted,
    ec2_ami_public,
    ec2_ami_aged,
    cloudtrail_s3_bucket_public,
    cloudtrail_no_cloudwatch,
    cloudtrail_s3_no_logging,
    acm_cert_expiring,
    lambda_deprecated_runtime,
    lambda_no_dlq,
    rds_no_deletion_protection,
    rds_no_multi_az,
    secrets_no_rotation,
    ssm_plaintext_secret,
    elb_no_access_logs,
    elb_weak_tls,
    dynamodb_no_pitr,
    dynamodb_no_encryption,
    sns_no_encryption,
    sqs_no_encryption,
]
